### ISSUE TITLE
Battle: Meteor Knight Fight

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/Prophets-of-the-Labyrinth#134]
Labyrinths: Castle of the Celestial Knights, Everything Bagel
Battle composed of: Earthly Knight (Earth), Meteor Knight (Fire), Earthly Knight (Earth)

Action ideas:
- Meteor Knight: bouncing attack
- Crits give protection/hp (Celestial Knight Insignia)
- Multi-hit

**Comment by doubledh** [comment]
My proposal:

Earthly Knight:
- Call Asteroid: brings in Asteroid ad
- Damping Wallop: damage + strip buff
- Quaking Smash: 0 base dmg, aoe stagger

Asteroid: SUPER SLOW (trying to get buffed by MKnight), low health and poise (meant to be taken out in 1-2 hits, and insta-stunned)
- Fragment: self takes minor dmg, and deals dmg to adventurer
- Bolide Burst: for each fraction of health remaining out of max, deal damage to a random adventurer + Knocks self out.
- On KO: dmg all enemy (self-team) combatants (increased by Power Up)

Meteor Knight: low poise, slow (trying to buff asteroids, but also trying to let adventurers gain protect)
- Sonic Slash: priority + dmg
- Incandescent Glare: increases protection of target by up to 50% (but no more than this move is prepared to deal) , then deals >avg dmg, and also receives recoil equal to 50% of dmg blocked
- Freefall Flare-up: Applies a notable amount of Power Up to both adventurers and enemies.

Earthly knight calls in ads, Meteor Knight buffs the Earthly Knight, the ads, AND adventurers, but the Earthly knights try stunning/buff-stripping the empowered adventurers. Asteroid tries to multiply the buff from Meteor Knight but also serves as hubris

**Comment by ntseng** [comment]
Overall looks like it'll add good variety! Some initial thoughts:

We don't currently have an "on death" timing trigger. My main concerns with adding one are design based rather than technically based. I want to limit the number of different trigger windows, because long trigger chains pack a lot of seemingly unrelated effects into the same move. We would already be able to get three levels deep with existing mechanics. For example: a combatant uses a move with its own effects, which triggers Poison, which kills them then triggers an "on death" effect. I'm also a little concerned about learnability: many Star Rail on-death effects are represented by a buff (or debuff), but in PotL, we aren't sure the party has modifiers reading, and if it wasn't buff/debuff based, the players would have to either read each monster entry as they encounter them or be surprised by the effect in their first encounter.

Maybe we should name Incandescent Glare something like "Head on Collision", I wasn't expecting it to be reflectable from the name.

**Comment by doubledh** [comment]
Incandescent Glare -> Armor Avalanche
