### ISSUE TITLE
Select archetypes

### ISSUE THREAD

**Issue by JakDaxe** [Imaginary-Horizons-Productions/Prophets-of-the-Labyrinth#148]
I tried to play it, when i press “Select Archetype” in the new adventure, nothing happens. I think it even crashes the bot.

**Comment by ntseng** [comment]
Initial investigations indicate it's related to a player profile not being created for new players, thus not having a list of archetypes to provide for the player to select. Thanks for bringing this to my attention!

**Comment by JakDaxe** [comment]
No problem, was just trying to play with a few people and we just couldn’t, thats why i pointed it out. Hope it gets fixed soon.

**Comment by ntseng** [comment]
The hotfix for this should be live. Let me know if you run into any other problems!
