### ISSUE TITLE
Add "Player Scaling" glossary page

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/Prophets-of-the-Labyrinth#422]
This page should explain what changes with large/smaller party sizes and how difficulty increases non-linearly to match player information coverage with more predicts in addition to action economy.

**Comment by doubledh** [comment]
is this supposed to be high-level explanation, or down to specifics and needs-to-be-maintained/linked to other docs?

**Comment by ntseng** [comment]
High level explanation. Specifics are going to be documented on the enemy's individual pages (via the new `[ ] vs < >` syntax)
