### ISSUE TITLE
Merchant Variant: Healing

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/Prophets-of-the-Labyrinth#425]
Provides healing for a price, perhaps scaling with repeats

**Comment by doubledh** [comment]
could make a healthcare joke here in at least one variant 😅

**Comment by ntseng** [comment]
This was inspired be one of your comments. Did you have multiple variants to propose?

**Comment by ntseng** [comment]
Obsoleted by game design moving toward Invariant Service Rooms
