### ISSUE TITLE
Game UX: Sniping Pet Targets

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/Prophets-of-the-Labyrinth#485]
Because pets pick targets before the round they act, the party can finish off the pet's selected target, and then make the pet look extra silly for targeting a foe that had been killed in a previous round.

The Beast Master doesn't predict who the pets are targeting, so it might be viable to have the pets check if their target is dead and reselect on the round they act if a better solution isn't found.

**Comment by doubledh** [comment]
could have the pets just select their target at time-of for their attacks in general (pick a target on-resolution)

minus if an enemy would proc anything by being targeted by a pet (though I don't think there's any of that in current implementation)

**Comment by ntseng** [comment]
Yeah, that probably works. I guess there's a part of me that really wants the Beast Tamer to be able to read who the pet's targeting, so that the hypothetical pet that puts Exposed on a random foe can be coordinated with.

**Comment by ntseng** [comment]
Going to make it so Beast Tamer can see who pets are targeting and leave it there; being informed to avoid sniping pet targets is value for that predict.
