### ISSUE TITLE
Gear Variant: Covering

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/Prophets-of-the-Labyrinth#497]
Targets an ally, replaces the target with the user as a target in all enemy moves

**Comment by doubledh** [comment]
does covering not cover "all-enemies" AOE from enemies?

**Comment by ntseng** [comment]
In the original imagining, Covering would include AoE, potentially getting the user hit multiple times by the same AoE. However, I've so far forgotten to add Covering variants in the gear overhaul, so we might have to either pick a place to add it or cut the mechanic.

**Comment by ntseng** [comment]
Confirmed no space in standard gear pool; didn't replace other effects because Covering is too feast or famine and multiplayer reliant.
